// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybesgznivndxakqfcxet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZXNnem5pdm5keGFrcWZjeGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTIzMTAsImV4cCI6MjA3NDQyODMxMH0.9eDPp4GgA8Bi-BqftsDPJGQ7WAENR_jCGDWw2W0YHBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});